categories:
  - Groceries
  - Restaurants_Takeout
  - Alcohol
  - Household
  - Kids
  - Health_Personal_Care
  - Home_Improvement
  - Clothing
  - Pets
  - Gifts
  - Electronics
  - Subscriptions
  - Gas_Auto
  - Travel
  - Unknown_Review
