"02 Costco": "02 Household Operations"
"03 Alcohol and bars": "03 Alcohol"
"03 Entertainment other": "03 Entertainment"
"03 Not home cooked foods:Bars": "03 Restaurants and Takeout:Restaurants"
"03 Not home cooked foods:Coffee Shops": "03 Restaurants and Takeout:Coffee Shops"
"03 Not home cooked foods:Restaurants": "03 Restaurants and Takeout:Restaurants"
"03 Not home cooked foods:Takeout & Fast": "03 Restaurants and Takeout:Takeout & Fast"
"Auto & Transport:Car Insurance": "01 Insurance:Car Insurance"
"Auto & Transport:Car Payment": "01 Debt Payments:Car Payment"
"Auto & Transport:Gas & Fuel": "02 Transportation:Gas & Fuel"
"Auto & Transport:Registration": "02 Transportation:Registration"
"Auto & Transport:Service & Parts": "02 Transportation:Service & Parts"
"Kids:Babysitter & Daycare": "01 Kids Fixed:Babysitter & Daycare"
"Personal Care": "02 Personal Care"
"Personal Care:Hair": "02 Personal Care:Hair"
"Subscriptions": "01 Subscriptions"
"Fitness": "02 Fitness"
"Dates": "03 Dates"
"Dates:Future dates": "03 Dates:Future Dates"
"Groceries": "02 Groceries and Foods"
"Shopping": "03 Shopping"
